server:
  port: 8081

spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/bysj?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://118.31.175.159:3306/faq?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      uri: mongodb://118.31.175.159:27017/bysj
  redis:
    database: 0
    host: 118.31.175.159
    port: 6380
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  typeAliasesPackage: com.zjj.faq.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#mapper:
#  mappers: com.zjj.faq.mappers.BaseMapper
#  identity: mysql


logging:
  file:
    name: log/log.log


